default_stages:
  - commit

repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black -t py310 -l 79 .
        language: system
        types: [python]
        pass_filenames: false
      - id: autoflake
        name: autoflake
        entry: autoflake
        language: system
        types: [python]
        args: [--in-place, --remove-all-unused-imports, --remove-duplicate-keys]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", "--line-length=79"]

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-docstring-first
        stages:
          - commit
          - push
      - id: check-merge-conflict
        stages:
          - push
      - id: trailing-whitespace
        stages:
          - commit
          - push
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: \.svg$
